# Generated by Django 3.1.1 on 2022-06-24 07:29

from django.db import migrations, models
import webook.arrangement.models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0010_auto_20220614_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from=['name', 'created'], unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='my_events', to='arrangement.Person', verbose_name='People'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='arrangement.Room', verbose_name='Rooms'),
        ),
    ]
