# Generated by Django 3.1.1 on 2021-11-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0010_timelineevent_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='end_of_business_hours',
            field=models.TimeField(verbose_name='End Of Business Hours'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='start_of_business_hours',
            field=models.TimeField(verbose_name='Start Of Business Hours'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='is_personal',
            field=models.BooleanField(default=True, verbose_name='Is Personal'),
        ),
    ]
