# Generated by Django 3.1.1 on 2021-11-24 08:59

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0010_timelineevent_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audience',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetype',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audience',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='end_of_business_hours',
            field=models.TimeField(verbose_name='End Of Business Hours'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='start_of_business_hours',
            field=models.TimeField(verbose_name='Start Of Business Hours'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='is_personal',
            field=models.BooleanField(default=True, verbose_name='Is Personal'),
        ),
    ]
