# Generated by Django 3.1.1 on 2022-06-24 07:33

from django.db import migrations
import webook.arrangement.models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0011_auto_20220624_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
