# Generated by Django 3.1.1 on 2021-11-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0011_auto_20211129_1139'),
        ('arrangement', '0011_auto_20211124_0959'),
    ]

    operations = [
    ]
