# Generated by Django 3.1.1 on 2021-12-30 09:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0014_arrangement_responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrangementSchematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeriesEventRepetitionInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('interval_days', models.IntegerField(verbose_name='Interval in days')),
                ('times_to_repeat', models.IntegerField(verbose_name='Times to repeat')),
                ('from_date', models.DateField(verbose_name='From date')),
                ('to_date', models.DateField(verbose_name='To date')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchematicEventTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('start', models.TimeField(verbose_name='Start')),
                ('end', models.TimeField(verbose_name='End')),
                ('people', models.ManyToManyField(to='arrangement.Person')),
                ('repetition_instruction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arrangement.serieseventrepetitioninstruction')),
                ('rooms', models.ManyToManyField(to='arrangement.Room')),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arrangement.arrangementschematic')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
