# Generated by Django 3.1.1 on 2022-01-13 09:17

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0015_arrangementschematic_schematiceventtemplate_serieseventrepetitioninstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arrangement.arrangement')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='schematiceventtemplate',
            name='people',
        ),
        migrations.RemoveField(
            model_name='schematiceventtemplate',
            name='repetition_instruction',
        ),
        migrations.RemoveField(
            model_name='schematiceventtemplate',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='schematiceventtemplate',
            name='schematic',
        ),
        migrations.DeleteModel(
            name='ArrangementSchematic',
        ),
        migrations.DeleteModel(
            name='SchematicEventTemplate',
        ),
        migrations.DeleteModel(
            name='SeriesEventRepetitionInstruction',
        ),
        migrations.AddField(
            model_name='event',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='arrangement.eventserie'),
        ),
    ]
