# Generated by Django 3.1.1 on 2022-01-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0016_auto_20220113_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='primary_color',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='AllDay'),
        ),
    ]
