# Generated by Django 3.1.1 on 2022-08-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0017_auto_20220630_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangement',
            name='display_text',
        ),
        migrations.RemoveField(
            model_name='arrangement',
            name='display_text_en',
        ),
        migrations.AddField(
            model_name='event',
            name='display_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen Display Text'),
        ),
        migrations.AddField(
            model_name='event',
            name='display_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen Display Text(English)'),
        ),
    ]
