# Generated by Django 3.1.1 on 2022-01-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0017_auto_20220113_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='primary_color',
            new_name='color',
        ),
    ]
