# Generated by Django 3.1.1 on 2022-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0020_looseservicerequisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='notes',
            field=models.ManyToManyField(related_name='arrangements', to='arrangement.Note', verbose_name='Notes'),
        ),
    ]
