# Generated by Django 3.1.1 on 2022-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0021_arrangement_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looseservicerequisition',
            name='event',
        ),
        migrations.AddField(
            model_name='looseservicerequisition',
            name='events',
            field=models.ManyToManyField(related_name='loose_requisitions', to='arrangement.Event', verbose_name='Events'),
        ),
    ]
