# Generated by Django 3.1.1 on 2022-02-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0022_auto_20220214_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='looseservicerequisition',
            name='comment',
            field=models.TextField(default='', verbose_name='Comment'),
        ),
    ]
