# Generated by Django 3.1.1 on 2022-02-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0023_looseservicerequisition_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looseservicerequisition',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='loose_requisitions',
            field=models.ManyToManyField(related_name='events', to='arrangement.LooseServiceRequisition', verbose_name='Loose service requisitions'),
        ),
    ]
