# Generated by Django 3.1.1 on 2022-02-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0024_auto_20220215_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='looseservicerequisition',
            name='arrangement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='loose_service_requisitions', to='arrangement.arrangement'),
            preserve_default=False,
        ),
    ]
