# Generated by Django 3.1.1 on 2022-02-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0025_looseservicerequisition_arrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='stages',
            field=models.CharField(choices=[('planning', 'planning'), ('requisitioning', 'requisitioning'), ('ready_to_launch', 'ready_to_launch'), ('in_production', 'in_production')], default='planning', max_length=255),
        ),
    ]
