# Generated by Django 3.1.1 on 2022-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0027_auto_20220218_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationreceipt',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='confirmationreceipt',
            name='confirmed_when',
        ),
        migrations.RemoveField(
            model_name='confirmationreceipt',
            name='guid',
        ),
        migrations.AddField(
            model_name='confirmationreceipt',
            name='code',
            field=models.CharField(db_index=True, default='a code', max_length=68, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmationreceipt',
            name='denial_reasoning',
            field=models.TextField(blank=True, verbose_name='Reason of denial'),
        ),
        migrations.AddField(
            model_name='confirmationreceipt',
            name='state',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('denied', 'denied'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmationreceipt',
            name='sent_to',
            field=models.EmailField(max_length=255, verbose_name='SentTo'),
        ),
    ]
