# Generated by Django 3.1.1 on 2022-02-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0028_auto_20220220_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Is Locked'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_requisitionally_complete',
            field=models.BooleanField(default=False, verbose_name='Requisitions Finished'),
        ),
    ]
