# Generated by Django 3.1.1 on 2022-02-21 08:11

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0030_event_silo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='looseservicerequisition',
            name='is_open_for_ordering',
            field=models.BooleanField(default=False, verbose_name='Is Open for Ordering'),
        ),
        migrations.AlterField(
            model_name='event',
            name='silo',
            field=models.CharField(choices=[('planning_silo', 'planning_silo'), ('requisitioning_silo', 'requisitioning_silo'), ('production_silo', 'production_silo')], default='planning_silo', max_length=255),
        ),
        migrations.CreateModel(
            name='RequisitionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type_of_requisition', models.CharField(choices=[('undefined', 'undefined'), ('people', 'people'), ('services', 'services')], default='undefined', max_length=255)),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='Is Fulfilled')),
                ('affected_events', models.ManyToManyField(to='arrangement.Event', verbose_name='Affected Events')),
                ('associated_confirmation_receipt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arrangement.confirmationreceipt')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='looseservicerequisition',
            name='ordered_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.orderedservice', verbose_name='Ordered service'),
        ),
    ]
