# Generated by Django 3.1.1 on 2022-02-21 10:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0031_auto_20220221_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionrecord',
            name='has_been_locked',
            field=models.BooleanField(default=False, verbose_name='Has been locked'),
        ),
        migrations.AlterField(
            model_name='event',
            name='silo',
            field=models.CharField(choices=[('planning_silo', 'planning_silo'), ('requisitioning_silo', 'requisitioning_silo'), ('analysis_silo', 'analysis_silo'), ('production_silo', 'production_silo')], default='planning_silo', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitionrecord',
            name='associated_confirmation_receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.confirmationreceipt'),
        ),
        migrations.CreateModel(
            name='CollisionAnalysisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('generated_for', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arrangement.arrangement')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollisionAnalysisRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dimension', models.CharField(choices=[('dimension_person', 'dimension_person'), ('dimension_room', 'dimension_room')], default='dimension_undefined', max_length=255)),
                ('collided_with_event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='collision_records_bystanded', to='arrangement.event')),
                ('conflicted_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.person')),
                ('conflicted_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.room')),
                ('originator_event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='collision_records_focal', to='arrangement.event')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='records', to='arrangement.collisionanalysisreport')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
