# Generated by Django 3.1.1 on 2022-02-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0032_auto_20220221_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collisionanalysisrecord',
            name='originator_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collision_records_focal', to='arrangement.event'),
        ),
    ]
