# Generated by Django 3.1.1 on 2022-02-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0033_auto_20220221_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='services_providable',
            field=models.ManyToManyField(related_name='providers', to='arrangement.ServiceType', verbose_name='Services providable'),
        ),
    ]
