# Generated by Django 3.1.1 on 2022-02-22 07:27

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0034_organization_services_providable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='services_providable',
        ),
        migrations.CreateModel(
            name='ServiceProvidable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('service_contact', models.EmailField(max_length=254, verbose_name='Service contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services_providable', to='arrangement.organization', verbose_name='Organization')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='providers', to='arrangement.servicetype', verbose_name='Service Type')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='eventservice',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services_provided', to='arrangement.serviceprovidable', verbose_name='Service Provider'),
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
