# Generated by Django 3.1.1 on 2022-02-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0036_auto_20220222_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationreceipt',
            name='code',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Code'),
        ),
    ]
