# Generated by Django 3.1.1 on 2022-02-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0037_auto_20220223_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedservice',
            name='state',
        ),
    ]
