# Generated by Django 3.1.1 on 2022-02-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0038_remove_orderedservice_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationreceipt',
            name='type',
            field=models.CharField(choices=[('requisition_default', 'requisition_default'), ('requisition_person', 'requisition_person'), ('requisition_service', 'requisition_service')], default='requisition_default', max_length=255),
        ),
    ]
