# Generated by Django 3.1.1 on 2022-02-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0040_auto_20220224_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='looseservicerequisition',
            name='generated_requisition_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.requisitionrecord'),
        ),
    ]
