# Generated by Django 3.1.1 on 2022-03-03 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0043_auto_20220303_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personrequisition',
            name='confirmation_receipt',
        ),
        migrations.RemoveField(
            model_name='personrequisition',
            name='historic_confirmation_receipts',
        ),
        migrations.RemoveField(
            model_name='servicerequisition',
            name='confirmation_receipt',
        ),
        migrations.RemoveField(
            model_name='servicerequisition',
            name='historic_confirmation_receipts',
        ),
        migrations.AddField(
            model_name='requisitionrecord',
            name='confirmation_receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requisition_record', to='arrangement.confirmationreceipt'),
        ),
        migrations.AddField(
            model_name='requisitionrecord',
            name='historic_confirmation_receipts',
            field=models.ManyToManyField(to='arrangement.ConfirmationReceipt'),
        ),
    ]
