# Generated by Django 3.1.1 on 2022-03-16 11:37

import autoslug.fields
from django.db import migrations, models
import django_extensions.db.fields
import webook.utils.crudl_utils.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0044_auto_20220303_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrangementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Arrangement',
                'verbose_name_plural': 'Arrangements',
            },
            bases=(models.Model, webook.utils.crudl_utils.model_mixins.ModelNamingMetaMixin),
        ),
        migrations.AlterModelOptions(
            name='arrangement',
            options={'verbose_name': 'Arrangement', 'verbose_name_plural': 'Arrangements'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='audience',
            options={'verbose_name': 'Audience', 'verbose_name_plural': 'Audiences'},
        ),
        migrations.AlterModelOptions(
            name='businesshour',
            options={'verbose_name': 'Business Hour', 'verbose_name_plural': 'Business Hours'},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Calendar', 'verbose_name_plural': 'Calendars'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'verbose_name': 'Organization Type', 'verbose_name_plural': 'Organization Types'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Service Type', 'verbose_name_plural': 'Service Types'},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'verbose_name': 'Timeline Event', 'verbose_name_plural': 'Timeline Events'},
        ),
        migrations.AlterField(
            model_name='confirmationreceipt',
            name='sent_when',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='SentWhen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='silo',
            field=models.CharField(choices=[('planning_silo', 'planning_silo'), ('requisitioning_silo', 'requisitioning_silo'), ('analysis_silo', 'analysis_silo'), ('production_silo', 'production_silo'), ('archive_silo', 'archive_silo')], default='planning_silo', max_length=255),
        ),
    ]
