# Generated by Django 3.1.1 on 2022-03-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0045_auto_20220316_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='arrangement_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='arrangement.arrangementtype', verbose_name='Arrangement Type'),
        ),
    ]
