# Generated by Django 3.1.1 on 2022-03-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0047_arrangement_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='show_on_multimedia_screen',
            field=models.BooleanField(default=False, verbose_name='Show on multimedia screen'),
        ),
    ]
