# Generated by Django 3.1.1 on 2022-03-28 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0049_auto_20220328_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='confirmationreceipt',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.note', verbose_name='Note'),
        ),
    ]
