# Generated by Django 4.2.10 on 2025-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0058_alter_eventserie_serie_plan_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmanifest',
            name='calculated_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
