# Generated by Django 4.2.10 on 2025-02-25 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.detail
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0058_alter_eventserie_serie_plan_manifest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('name', models.CharField(max_length=512)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('is_template', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('awaiting', 'Awaiting'), ('denied', 'Denied'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('changed', 'Changed'), ('template', 'Template'), ('in_revision', 'In Revision')], default='awaiting', max_length=15)),
                ('freetext_comment', models.TextField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderProcessingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=512)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('related_to_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='arrangement.serviceorder')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GetServicePersonellJsonView',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arrangement.service')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('arrangement.service', django.views.generic.detail.DetailView),
        ),
        migrations.CreateModel(
            name='ServiceOrderProvision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('freetext_comment', models.TextField(blank=True)),
                ('comment_to_personell', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by')),
                ('for_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='arrangement.event')),
                ('related_to_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='arrangement.serviceorder')),
                ('selected_personell', models.ManyToManyField(blank=True, null=True, related_name='interim_provisions_assigned_to', to='arrangement.person')),
                ('sopr_resolving_this', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_resolved_provisions', to='arrangement.serviceorderprocessingrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderPreconfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('title', models.CharField(max_length=512)),
                ('message', models.TextField()),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by')),
                ('assigned_personell', models.ManyToManyField(blank=True, related_name='associated_with_preconfigurations', to='arrangement.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.person')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preconfigurations', to='arrangement.service')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderInternalChangelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('changelog_message', models.TextField(max_length=5024)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='arrangement.serviceorder')),
                ('source_sopr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arrangement.serviceorderprocessingrequest')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderChangeSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('original_state_of_service_order', models.CharField(choices=[('awaiting', 'Awaiting'), ('denied', 'Denied'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('changed', 'Changed'), ('template', 'Template'), ('in_revision', 'In Revision')], default='awaiting', max_length=15)),
                ('has_been_processed', models.BooleanField(default=False)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='change_summaries', to='arrangement.serviceorder')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderChangeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('initial_start', models.DateTimeField()),
                ('initial_end', models.DateTimeField()),
                ('type_of_change', models.CharField(choices=[('new', 'New'), ('times_changed', 'Times Changed'), ('removed', 'Removed')], default='new', max_length=15)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by')),
                ('provision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.serviceorderprovision')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='arrangement.serviceorderchangesummary')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='applied_preconfiguration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='applied_to', to='arrangement.serviceorderpreconfiguration'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='assigned_personell',
            field=models.ManyToManyField(related_name='services_assigned_to', to='arrangement.person'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='associated_manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='arrangement.planmanifest'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.person'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='events',
            field=models.ManyToManyField(related_name='orders', to='arrangement.event'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='associated_lines', to='arrangement.service'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='template_for',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='emails',
            field=models.ManyToManyField(related_name='services', to='arrangement.serviceemail'),
        ),
        migrations.AddField(
            model_name='service',
            name='events',
            field=models.ManyToManyField(to='arrangement.event'),
        ),
        migrations.AddField(
            model_name='service',
            name='resources',
            field=models.ManyToManyField(related_name='responsible_for_services', to='arrangement.person'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('title', models.CharField(max_length=248)),
                ('source', models.CharField(max_length=512)),
                ('icon_class', models.CharField(max_length=50, null=True)),
                ('icon_background_class', models.CharField(max_length=50, null=True)),
                ('url_label', models.CharField(max_length=100, null=True)),
                ('reference_to_url', models.URLField(max_length=512, null=True, verbose_name='Reference URL')),
                ('message', models.TextField(max_length=5012)),
                ('is_seen', models.BooleanField(default=False)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='arrangement.person')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
