# Generated by Django 4.2.10 on 2025-03-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0059_planmanifest_calculated_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='original_date',
            field=models.DateField(blank=True, null=True, verbose_name='Original Date'),
        ),
    ]
