# Generated by Django 4.2.10 on 2025-04-10 09:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0060_serviceemail_archived_by_serviceemail_archived_when_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='state',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('denied', 'Denied'), ('confirmed', 'Confirmed'), ('maybe', 'Maybe'), ('provisioned', 'Provisioned'), ('cancelled', 'Cancelled'), ('changed', 'Changed'), ('template', 'Template'), ('in_revision', 'In Revision')], default='awaiting', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceorderchangesummary',
            name='original_state_of_service_order',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('denied', 'Denied'), ('confirmed', 'Confirmed'), ('maybe', 'Maybe'), ('provisioned', 'Provisioned'), ('cancelled', 'Cancelled'), ('changed', 'Changed'), ('template', 'Template'), ('in_revision', 'In Revision')], default='awaiting', max_length=15),
        ),
        migrations.CreateModel(
            name='ServiceOrderEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('event_type', models.CharField(choices=[('response_given', 'Response Given'), ('order_finalized', 'Order Finalized'), ('provisioning_started', 'Provisioning Started')], default='response_given', max_length=20)),
                ('value', models.TextField(blank=True, help_text='The value of the event log', null=True, verbose_name='Value')),
                ('comment', models.TextField(blank=True, help_text='The comment of the event log', null=True, verbose_name='Comment')),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='service_order_event_logs', to='arrangement.person')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event_logs', to='arrangement.serviceorder')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
