# Generated by Django 4.2.10 on 2025-03-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0060_event_original_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Is Disabled'),
        ),
    ]
