# Generated by Django 4.2.10 on 2025-04-14 11:55

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0061_alter_serviceorder_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ServiceStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_creator', models.BooleanField(default=False, help_text='This person created the service')),
                ('can_respond_to_orders', models.BooleanField(default=False, help_text='This person can respond to orders')),
                ('can_provision_orders', models.BooleanField(default=False, help_text='This person can provision orders')),
                ('can_define_preconfigurations', models.BooleanField(default=False, help_text='This person can define preconfigurations')),
                ('can_administrate_personell', models.BooleanField(default=False, help_text='This person can add personell')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services_staffed', to='arrangement.person')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='arrangement.service')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
