# Generated by Django 4.2.10 on 2025-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0062_service_is_active_servicestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestaff',
            name='can_administrate_staff',
            field=models.BooleanField(default=False, help_text='This person can add staff'),
        ),
        migrations.AddField(
            model_name='servicestaff',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This person is active in this service'),
        ),
    ]
