# Generated by Django 4.2.10 on 2025-04-22 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0065_serviceroles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorderpreconfiguration',
            name='parent_preconfiguration',
        ),
        migrations.AddField(
            model_name='serviceorderpreconfiguration',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_children', to='arrangement.serviceorderpreconfiguration'),
        ),
    ]
