# Generated by Django 4.2.10 on 2025-04-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0066_remove_serviceorderpreconfiguration_parent_preconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderpreconfiguration',
            name='standard_choices',
            field=models.ManyToManyField(related_name='standard_choice_for', to='arrangement.serviceorderpreconfiguration'),
        ),
    ]
