# Generated by Django 4.2.10 on 2025-05-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0067_serviceorderpreconfiguration_standard_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderprocessingrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_requests', to='arrangement.person'),
        ),
    ]
