# Generated by Django 4.2.10 on 2025-05-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0069_servicenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenotification',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_notifications', to='arrangement.serviceorder'),
        ),
    ]
