# Generated by Django 4.2.10 on 2025-06-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0061_room_is_disabled'),
        ('arrangement', '0070_servicenotification_service_order'),
    ]

    operations = [
    ]
