# Generated by Django 4.2.10 on 2025-06-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0071_merge_20250602_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderchangeline',
            name='provision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.serviceorderprovision'),
        ),
        migrations.AlterField(
            model_name='serviceordereventlog',
            name='event_type',
            field=models.CharField(choices=[('response_given', 'Response Given'), ('order_finalized', 'Order Finalized'), ('provisioning_started', 'Provisioning Started'), ('cancelled', 'Cancelled')], default='response_given', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorderprovision',
            name='related_to_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='arrangement.serviceorder'),
        ),
    ]
