# Generated by Django 4.2.10 on 2025-03-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph_integration', '0007_syncedevent_is_degraded_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedevent',
            name='repeating_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='repeating_instances', to='graph_integration.syncedevent'),
        ),
        migrations.AlterField(
            model_name='syncedevent',
            name='event_type',
            field=models.CharField(choices=[('repeating', 'repeating'), ('repeating_instance', 'repeating_instance'), ('single', 'single')], default='single', max_length=20),
        ),
    ]
