from unicodedata import name
from django.urls import path
from webook.arrangement.views import (
    arrangement_list_view,
    arrangement_create_view,
    arrangement_update_view,
    arrangement_detail_view,
    arrangement_delete_view,
    planners_on_arrangement_view,
    planners_on_arrangement_table_view,
    arrangement_add_planner_form_view,
    arrangement_remove_planner_form_view,
    arrangement_promote_planner_to_main_view,
    arrangement_search_view
)


arrangement_urls = [
    path(
        route="arrangement/list/",
        view=arrangement_list_view,
        name="arrangement_list",
    ),
    path(
        route="arrangement/create/",
        view=arrangement_create_view,
        name="arrangement_create",
    ),
    path(
        route="arrangement/edit/<slug:slug>",
        view=arrangement_update_view,
        name="arrangement_edit",
    ),
    path(
        route="arrangement/<slug:slug>/",
        view=arrangement_detail_view,
        name="arrangement_detail",
    ),
    path(
        route="arrangement/delete/<slug:slug>",
        view=arrangement_delete_view,
        name="arrangement_delete",
    ),
    path(
        route="arrangement/planners",
        view=planners_on_arrangement_view,
        name="planners_on_arrangement",
    ),
    path(
        route="arrangement/add_planner",
        view=arrangement_add_planner_form_view,
        name="arrangement_add_planner",
    ),
    path(
        route="arrangement/remove_planner",
        view=arrangement_remove_planner_form_view,
        name="arrangement_remove_planner",
    ),
    path(
        route="arrangement/planners_table",
        view=planners_on_arrangement_table_view,
        name="arrangement_planners_table"
    ),
    path(
        route="arrangement/promote_to_main",
        view=arrangement_promote_planner_to_main_view,
        name="arrangement_promote_planner_to_main",
    ),
    path(
        route="arramgement/search",
        view=arrangement_search_view,
        name="arrangement_search",
    ),
]