from unicodedata import name
from django.urls import path
from webook.arrangement import views
from webook.arrangement.views import (
    plan_arrangement_view,
    plan_create_event,
    plan_get_events,
    plan_update_event,
    plan_delete_event,
    planner_view,
    plan_delete_events,
    plan_order_service_view,
    plan_create_events,
    get_collision_analysis_view,
    plan_get_loose_service_requisitions,
    plan_loose_service_requisitions_component_view,
    plan_people_requisitions_component_view,
    plan_people_to_requisition_component_view,
    planner_calendar_view,
    planner_arrangement_events_view,
    get_arrangements_in_period_view,
    arrangement_information_dialog_view,
    arrangement_calendar_planner_dialog_view,
    arrangement_create_simple_event_dialog_view,
    arrangement_create_serie_dialog_view,
    arrangement_promote_planner_dialog_view,
    arrangement_new_note_dialog_view,
    arrangement_add_planner_dialog_view,
    arrangement_add_planners_form_view,
    arrangement_remove_planners_form_view
)


planner_urls = [
    path(
        route="planner/planner",
        view=planner_view,
        name="planner",
    ),
    path(
        route="planner/plan",
        view=plan_arrangement_view,
        name="plan_arrangement"
    ),
    path(
        route="planner/create_event",
        view=plan_create_event,
        name="plan_create_event"
    ),
    path(
        route="planner/get_events",
        view=plan_get_events,
        name="plan_get_events",
    ),
    path(
        route="planner/update_event/<int:pk>",
        view=plan_update_event,
        name="plan_update_event",
    ),
    path(
        route="planner/delete_event/<int:pk>",
        view=plan_delete_event,
        name="plan_delete_event"
    ),
    path(
        route="planner/delete_events/",
        view=plan_delete_events,
        name="plan_delete_events",
    ),
    path(
        route="planner/order_service/",
        view=plan_order_service_view,
        name="plan_order_service",
    ),
    path(
        route="planner/create_events/",
        view=plan_create_events,
        name="plan_create_events",
    ),
    path(
        route="planner/get_collision_analysis/",
        view=get_collision_analysis_view,
        name="get_collision_analysis",
    ),
    path(
        route="planner/loose_service_requisitions",
        view=plan_get_loose_service_requisitions,
        name="get_loose_service_requisitions",
    ),
    path(
        route="planner/loose_service_requisitions_table",
        view=plan_loose_service_requisitions_component_view,
        name="loose_service_requisitions_table_component",
    ),
    path(
        route="planner/people_requisitions_table",
        view=plan_people_requisitions_component_view,
        name="people_requisitions_table_component",
    ),
    path(
        route="planner/people_to_requisition_table",
        view=plan_people_to_requisition_component_view,
        name="people_to_requisition_table_component"
    ),
    path(
        route="planner/calendar",
        view=planner_calendar_view,
        name="planner_calendar",
    ),
    path(
        route="planner/arrangements_as_events",
        view=planner_arrangement_events_view,
        name="arrangement_events",
    ),
    path(
        route="planner/arrangements_in_period",
        view=get_arrangements_in_period_view,
        name="arrangements_in_period"
    ),
    path(
        route="planner/dialogs/arrangement_information/<slug:slug>",
        view=arrangement_information_dialog_view,
        name="arrangement_dialog",
    ),
    path(
        route="planner/dialogs/arrangement_calendar_planner/<slug:slug>",
        view=arrangement_calendar_planner_dialog_view,
        name="arrangement_planner_dialog",
    ),
    path(
        route="planner/dialogs/create_simple_event",
        view=arrangement_create_simple_event_dialog_view,
        name="arrangement_create_event_dialog"
    ),
    path(
        route="planner/dialogs/create_serie",
        view=arrangement_create_serie_dialog_view,
        name="arrangement_create_serie_dialog",
    ),
    path(
        route="planner/dialogs/promote_main_planner",
        view=arrangement_promote_planner_dialog_view,
        name="arrangement_promote_main_planner_dialog",
    ),
    path(
        route="planner/dialogs/new_note",
        view=arrangement_new_note_dialog_view,
        name="arrangement_new_note_dialog",
    ),
    path(
        route="planner/dialogs/add_planner",
        view=arrangement_add_planner_dialog_view,
        name="arrangement_add_planner_dialog",
    ),
    path(
        route="planner/add_planners",
        view=arrangement_add_planners_form_view,
        name="arrangement_add_planners_form",
    ),
    path(
        route="planner/remove_planners",
        view=arrangement_remove_planners_form_view,
        name="arrangement_remove_planners_form"
    )
]