from unicodedata import name

from django.urls import path

from webook.arrangement.views.service_views import *

service_urls = [
    path(
        route="service/dashboard",
        view=services_dashboard_view,
        name="services_dashboard",
    ),
    path(
        route="service/json/list",
        view=services_json_list_view,
        name="services_json_list",
    ),
    path(
        route="service/add_email/<int:pk>",
        view=services_add_email_view,
        name="services_add_email",
    ),
    path(
        route="service/add_person/<int:pk>",
        view=services_add_person_view,
        name="services_add_person",
    ),
    path(
        route="service/preconfiguration/<int:pk>/add_person",
        view=service_preconfiguration_add_person_view,
        name="service_preconfiguration_add_person",
    ),
    path(
        route="service/<int:id>/toggle",
        view=toggle_service_active_json_view,
        name="service_deactivate",
    ),
    path(
        route="service/create",
        view=create_service_view,
        name="services_create",
    ),
    path(
        route="service/<int:pk>/update",
        view=update_service_view,
        name="services_update",
    ),
    path(
        route="service/delete_email",
        view=delete_service_email_from_service_view,
        name="service_delete_email",
    ),
    path(
        route="service/create_template",
        view=create_service_template_view,
        name="create_service_template",
    ),
    path(
        route="service/process/<str:token>",
        view=process_service_request_view,
        name="process_service_order",
    ),
    path(
        route="service/process/<str:token>/provisions",
        view=get_provisions_json_view,
        name="get_provisions_json_view",
    ),
    path(
        route="service/changenote/<str:token>",
        view=create_change_log_note_view,
        name="create_change_note_view",
    ),
    path(
        route="service/provisioning/<str:token>/<int:provision>",
        view=provision_personell_form_view,
        name="provision_personell_form",
    ),
    path(
        route="service/provisioning/<str:token>/resource/events/<int:person_id>",
        view=get_events_for_resource_in_sopr_json_view,
        name="get_events_for_sopr_resource",
    ),
    path(
        route="service/provisioning/deny",
        view=deny_service_order_form_view,
        name="deny_service_order",
    ),
    path(
        route="service/provisioning/confirm",
        view=confirm_service_order_form_view,
        name="confirm_service_order",
    ),
    path(
        route="service/<int:id>/calendar/orders",
        view=get_service_overview_calendar,
        name="service_orders_calendar_json",
    ),
    path(
        route="service/cancel",
        view=cancel_service_order_form_view,
        name="cancel_service_order",
    ),
    path(
        route="service/open_for_revision/<str:token>",
        view=open_service_order_for_revisioning_form_view,
        name="open_service_order_for_revision",
    ),
    path(
        route="service/view/<int:id>", view=service_detail_view, name="service_detail"
    ),
    path(
        route="service/<int:service>/personnell",
        view=service_personnell_json_list_view,
        name="service_personnell",
    ),
    path(
        route="service/<int:service>/orders",
        view=service_orders_for_service_json_list_view,
        name="service_orders_json_list",
    ),
    path(
        route="service/process_redirect/<int:order>",
        view=redirect_to_process_service_request_view,
        name="redirect_process_service_order_view",
    ),
    path(
        route="service/<int:service>/responsibles",
        view=get_service_responsibles_json_view,
        name="get_service_responsibles_view",
    ),
    path(
        route="service/<int:service>/preconfigurations",
        view=get_preconfigurations_for_service_json_view,
        name="get_preconfigurations_view",
    ),
    path(
        route="service/preconfigurations/delete/<int:id>",
        view=archive_preconfiguration_json_view,
        name="delete_preconfiguration_view",
    ),
    path(
        route="service/preconfigurations/create",
        view=create_preconfiguration_json_view,
        name="create_preconfiguration_view",
    ),
    path(
        route="service/preconfigurations/<int:id>/update",
        view=update_preconfiguration_json_view,
        name="update_preconfiguration",
    ),
    path(
        route="service/changesummary/<str:token>",
        view=get_change_summary_json_view,
        name="get_change_summary_view",
    ),
    path(
        route="service/personell/<str:token>/<int:provision_id>",
        view=get_personell_available_for_order_json_view,
        name="get_personell_available_for_order_json_view",
    ),
    path(
        route="service/<int:id>/personell",
        view=get_service_personell_json_view,
        name="get_service_personell_json_view",
    ),
    path(
        route="service/tree",
        view=service_tree_json_view,
        name="service_tree_json_view",
    ),
    path(
        route="service/<int:id>/personellEvents",
        view=get_service_personell_fc_calendar_json_view,
        name="get_service_personell_fc_calendar_json_view",
    ),
    path(
        route="service/<int:id>/allocate",
        view=service_order_allocation_view,
        name="service_order_allocation_view",
    ),
]
