# Generated by Django 4.2.10 on 2025-06-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
