# Generated by Django 4.2.10 on 2025-06-24 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskexecution_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
