# Generated by Django 4.2.10 on 2025-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskexecution_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
