# Generated by Django 4.2.10 on 2025-06-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskexecution_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='execution_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
