# Generated by Django 3.1.1 on 2021-11-23 08:57

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0010_timelineevent_stamp'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.person'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='_get_slug'),
        ),
    ]
