# Generated by Django 3.1.1 on 2021-12-09 07:22

from django.db import migrations, models
import webook.users.media_pathing


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=webook.users.media_pathing.profile_picture_path, verbose_name='Profile Picture'),
        ),
    ]
