# Generated by Django 3.1.1 on 2021-12-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211123_1021'),
        ('users', '0003_auto_20211209_0722'),
    ]

    operations = [
    ]
