# Generated by Django 3.1.1 on 2022-10-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220922_1540'),
        ('users', '0013_auto_20220927_1210'),
    ]

    operations = [
    ]
