# Generated by Django 3.1.1 on 2022-12-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20221003_1144'),
        ('users', '0014_auto_20221019_0810'),
    ]

    operations = [
    ]
