# Generated by Django 3.1.1 on 2023-01-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_is_user_admin'),
        ('users', '0016_auto_20230105_1510'),
    ]

    operations = [
    ]
