# Generated by Django 4.2.10 on 2025-06-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_usertokenrevocation_userresetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_service_admin',
            field=models.BooleanField(default=False, verbose_name='Service Administrator'),
        ),
    ]
